- hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:

    - name: Test repo module
      repo:
        username: "xxx"
        password: "xxx"
        repository: "poc-sample"
        project_key: "POC"
        state: "present"
