- hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:

    - name: Test repo_var module
      repo_var:
        username: "xxx"
        password: "xxx"
        repository: "poc-sample"
        variables:
          - name: user
            value: xxx
          - name: pass
            value: yyy
            secured: True
