- hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:

    - name: Test repo_perm module
      repo_perm:
        username: "xxx"
        password: "xxx"
        repository: "poc-sample"
        permissions:
          - type: group
            name: administrators
            perm: admin
          - type: group
            name: developers
            perm: write